# Generated by Django 4.0.6 on 2022-07-31 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docuclient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alldetail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics')),
                ('administrationClients', models.ManyToManyField(to='alldetail.administrationclient')),
                ('articles', models.ManyToManyField(to='alldetail.articles')),
                ('bonLivraisons', models.ManyToManyField(to='docuclient.bonlivraison')),
                ('categorys', models.ManyToManyField(to='alldetail.category')),
                ('clientParticuliers', models.ManyToManyField(to='alldetail.clientparticulier')),
                ('conventionEntrepriseClients', models.ManyToManyField(to='alldetail.conventionentrepriseclient')),
                ('devisClients', models.ManyToManyField(to='docuclient.devisclient')),
                ('entrepriseClients', models.ManyToManyField(to='alldetail.entrepriseclient')),
                ('factures', models.ManyToManyField(to='docuclient.facture')),
                ('products', models.ManyToManyField(to='alldetail.product')),
                ('ravites', models.ManyToManyField(to='docuclient.ravite')),
                ('shops', models.ManyToManyField(to='alldetail.shop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
