# Generated by Django 4.0.6 on 2022-07-24 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ravite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=255)),
                ('article_name', models.CharField(blank=True, max_length=255)),
                ('article_number', models.IntegerField()),
                ('article_description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partenary_code', models.CharField(blank=True, max_length=200, null=True)),
                ('reduction_number', models.FloatField(blank=True, null=True)),
                ('payment_modality', models.CharField(blank=True, choices=[('A échéance', 'A échéance'), ('Définis dans le contrat', 'Définis dans le contrat'), ('Journalier, hebdomadaire, mensuel', 'Journalier, hebdomadaire, mensuel')], max_length=200, null=True)),
                ('modalite_paiement', models.FloatField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('nation_choices', models.CharField(blank=True, choices=[('National', 'National'), ('International', 'International')], max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
                ('livraison', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DevisClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_modality', models.CharField(blank=True, choices=[('A échéance', 'A échéance'), ('Définis dans le contrat', 'Définis dans le contrat'), ('Journalier, hebdomadaire, mensuel', 'Journalier, hebdomadaire, mensuel')], max_length=200, null=True)),
                ('nation_choices', models.CharField(blank=True, choices=[('National', 'National'), ('International', 'International')], max_length=100, null=True)),
                ('client_type', models.CharField(blank=True, choices=[('Particuliers', 'Particuliers')], max_length=200, null=True)),
                ('client_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_Code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email_Address', models.EmailField(blank=True, max_length=200, null=True)),
                ('taxe_TPS', models.FloatField(blank=True, null=True)),
                ('taxe_CSS', models.FloatField(blank=True, null=True)),
                ('livraison', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=255)),
                ('client_service', models.CharField(blank=True, max_length=255, null=True)),
                ('client_address', models.CharField(max_length=300)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
